In [1]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.arange(6)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int32


In [18]:
# 2. Given a NumPy array 'arr', check if its data type is `float64`.
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print("The data type of the array is not float64.")

The data type of the array is float64.


In [3]:
# 3. Create a NumPy array 'arr' with a data type of `complex128` containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [4]:
# 4. Convert an existing NumPy array 'arr' of integers to `float32` data type.
arr = np.array([1, 2, 3, 4, 5])  # Sample integer array
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


In [5]:
# 5. Given a NumPy array 'arr' with `float64` data type, convert it to `float32` to reduce decimal precision.

arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)  # Example float64 array
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)

[1.1 2.2 3.3]
float32


In [6]:
# 6. Write a function `array_attributes` that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3])
print(array_attributes(arr))

((3,), 3, dtype('int32'))


In [7]:
# 7. Create a function `array_dimension` that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))

2


In [8]:
# 8. Design a function `item_size_info` that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes


arr = np.array([1, 2, 3], dtype=np.int32)
print(item_size_info(arr))

(4, 12)


In [9]:
# 9. Create a function `array_strides` that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))

(8, 4)


In [10]:
# 10. Design a function `shape_stride_relationship` that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))

((2, 3), (12, 4))


In [11]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [12]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 13. Write a function `generate_range_array` that takes three integers `start`, `stop`, and `step` as arguments and creates a NumPy array with a range starting from `start`, ending at `stop` (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [14]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with `num` equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(lst):
    return np.array(lst)

lst = [1, 2, 3, 4]
print(list_to_array(lst))

[1 2 3 4]


In [17]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()

print("Original array:", arr)
print("View of the array:", view_arr)

Original array: [1 2 3 4 5]
View of the array: [1 2 3 4 5]


In [19]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))  # Concatenates along rows
print(concatenate_arrays(arr1, arr2, axis=1))  # Concatenates along columns


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [20]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
result = np.concatenate((arr1, arr2), axis=0)  # Note: Changed to axis=0 for this example to match shapes
print(result)

[[1 2 3]
 [4 5 6]]


In [21]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack_arrays(arrays):
    return np.vstack(arrays)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(vertical_stack_arrays([arr1, arr2]))

[[1 2 3]
 [4 5 6]]


In [22]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range_array(start, end, step):
    return np.arange(start, end + 1, step)


print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [23]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def generate_equal_space_array():
    return np.linspace(0, 1, 10)


print(generate_equal_space_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [24]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def generate_log_space_array():
    return np.logspace(0, 3, 5)


print(generate_log_space_array())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [25]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0       15       75        5
1        1        2       21
2        1       65       90
3       18        8       35
4       92       35       97


In [26]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negatives(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {'A': [1, -2, 3], 'B': [-4, 5, -6]}
df = pd.DataFrame(data)
print(replace_negatives(df, 'A'))

   A  B
0  1 -4
1  0  5
2  3 -6


In [27]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [28]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


In [29]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_five = arr[arr > 5]
print(greater_than_five)

[ 8 10  7]


In [30]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print(sliced_array)

[3 4 5 6]


In [31]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [32]:
# 31. Write a NumPy function to extract elements in a specific order from a given 2D array based on indices provided in another array.

def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
print(extract_elements(arr, indices))

[2 6 7]


In [33]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 8, 3, 10])
print(filter_greater_than(arr, 5))

[ 8 10]


In [34]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_from_3d(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

# Example usage
arr = np.arange(27).reshape((3, 3, 3))
x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])
print(extract_from_3d(arr, x_indices, y_indices, z_indices))

[ 5 10 24]


In [35]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter_with_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

# Example usage
arr = np.array([1, 5, 8, 3, 10])
print(filter_with_conditions(arr, 3, 9))

[5 8]


In [36]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
print(extract_elements_2d(arr, row_indices, col_indices))

[2 6 7]


In [37]:
# 36. Given an array `arr` of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [38]:
# 37. Consider two arrays `arr1` of shape (1, 3) and `arr2` of shape (3, 4). Multiply each row of `arr2` by the corresponding element in `arr1` using NumPy broadcasting.

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = arr1.T * arr2
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [39]:
# 38. Given a 1D array `arr1` of shape (1, 4) and a 2D array `arr2` of shape (4, 3), add `arr1` to each row of `arr2` using NumPy broadcasting.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])
result = arr2 + arr1.reshape(-1, 1)
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [40]:
# 39. Consider two arrays `arr1` of shape (3, 1) and `arr2` of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [41]:
# 40. Given arrays `arr1` of shape (2, 3) and `arr2` of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

try:
    result = arr1 * arr2
except ValueError as e:
    print(f"Error: {e}")


Error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [42]:
# 41. Calculate column-wise mean for the given array.

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = arr.mean(axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [43]:
# 42. Find the maximum value in each row of the given array.

arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = arr.max(axis=1)
print(row_max)

[3 6]


In [44]:
# 43. For the given array, find indices of the maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = arr.argmax(axis=0)
print(max_indices)

[1 1 1]


In [45]:
# 44. For the given array, apply a custom function to calculate the moving sum along rows.

def moving_sum(arr, window_size):
    result = np.cumsum(arr, axis=1)
    result[:, window_size:] = result[:, window_size:] - result[:, :-window_size]
    return result[:, window_size-1:]

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr, 2))

[[ 3  5]
 [ 9 11]]


In [46]:
# 45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])
even_check = np.all(arr % 2 == 0, axis=0)
print(even_check)

[False False False]


In [47]:
# 46. Given a NumPy array `arr`, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
def reshape_matrix(arr, m, n):
    return arr.reshape((m, n))

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = reshape_matrix(arr, 2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [48]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
    return matrix.flatten()


matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened = flatten_matrix(matrix)
print(flattened)

[1 2 3 4 5 6]


In [49]:
# 48. Write a function that concatenates two given arrays along a specified axis.

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated = concatenate_arrays(array1, array2, axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
def split_array(arr, indices_or_sections, axis=0):
    return np.split(arr, indices_or_sections, axis)


arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = split_array(arr, 3)
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [51]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[ 1 10  4 11  5]


In [52]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(0, 10, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print(arr1)
print(arr2)
print(result)

[0 5 8 3 6 2 4 5 5 1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  7 11  7 11  8 11 13 14 11]


In [53]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [54]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print(arr1)
print(arr2)
print(result)

[6 4 1 9 6]
[1 2 3 4 5]
[ 6  8  3 36 30]


In [55]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [56]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2
print(result)

[ 1 16 27 16  5]


In [57]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

def count_substring(arr, substring):
    return np.char.count(arr, substring)


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring_count = count_substring(arr, 'hello')
print(substring_count)

[1 0 1 0 1]


In [62]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase(arr):
   
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])


arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)
print(uppercase_characters)


['H' 'W' 'OAI' 'GPT']


In [63]:
# 58. Replace occurrences of a substring in a NumPy array of strings with a new string.

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replaced_arr = replace_substring(arr, 'apple', 'fruit')
print(replaced_arr)

['fruit' 'banana' 'grape' 'pinefruit']


In [64]:
# 59. Concatenate strings in a NumPy array element-wise.

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_arr = concatenate_strings(arr1, arr2)
print(concatenated_arr)

['HelloOpen' 'WorldAI']


In [65]:
# 60. Find the length of the longest string in a NumPy array.

def longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print(longest_length)

9


In [66]:
# 61. Compute the mean, median, variance, and standard deviation of a dataset of 100 random integers between 1 and 1000.

dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)
print(mean, median, variance, std_dev)

490.72 510.5 72418.78159999999 269.1073793116792


In [67]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.uniform(1, 100, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(percentile_25, percentile_75)

30.779650617505666 76.29039536063439


In [68]:
# 63. Compute the correlation coefficient between two arrays.

x = np.random.randint(1, 100, 50)
y = np.random.randint(1, 100, 50)
correlation_coefficient = np.corrcoef(x, y)[0, 1]
print(correlation_coefficient)

0.09922681098957524


In [69]:
# 64. Perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])
matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)

[[ 58  64]
 [139 154]]


In [70]:
# 65. Calculate specific percentiles and quartiles of an array.
arr = np.random.randint(10, 1001, 50)
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)
first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)
print(percentile_10, percentile_50, percentile_90, first_quartile, third_quartile)

167.4 573.0 876.2 365.0 754.0


In [71]:
# 66. Find the index of a specific element in a NumPy array.

arr = np.array([1, 2, 3, 4, 5])
index_of_element = np.where(arr == 3)[0][0]
print(index_of_element)

2


In [72]:
# 67. Sort a random NumPy array in ascending order.

random_array = np.random.randint(1, 100, 10)
sorted_array = np.sort(random_array)
print(sorted_array)

[ 1 19 27 31 43 44 66 77 84 94]


In [73]:
# 68. Filter elements greater than 20 in a NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])
filtered_elements = arr[arr > 20]
print(filtered_elements)

[25 42 30]


In [74]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])
divisible_by_3 = arr[arr % 3 == 0]
print(divisible_by_3)

[12 15]


In [75]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
filtered_range = arr[(arr >= 20) & (arr <= 40)]
print(filtered_range)

[20 30 40]


In [76]:
# 71. Check the byte order of a NumPy array using the `dtype` attribute.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [77]:
# 72. Perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


In [78]:
# 73. Swap the byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print(swapped_arr)

[16777216 33554432 50331648]


In [79]:
# 74. Swap the byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.newbyteorder('S')  # Swap byte order
else:
    swapped_arr = arr.newbyteorder('=')
print(swapped_arr)

[16777216 33554432 50331648]


In [80]:
# 75. Check if byte swapping is necessary for the current system using the `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)
needs_byte_swap = arr.dtype.byteorder == '>'  # Big-endian check
print(needs_byte_swap)

False


In [81]:
# 76. Create a copy of `arr1`, modify `copy_arr`, and check if it affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print(arr1)  # Original array remains unchanged
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


In [82]:
# 77. Modify a slice from a 2D NumPy array and observe if it changes the original matrix.

matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print(matrix)  # Original matrix is changed
print(view_slice)

[[100   6   1]
 [  2   8   7]
 [  4   8   4]]
[[100   6]
 [  2   8]]


In [83]:
# 78. Broadcast addition of 5 to a slice and check if it alters the original array.

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, 1:3]
view_b += 5
print(array_a)  # Original array is changed
print(view_b)

[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]
[[10 11]
 [13 14]]


In [84]:
# 79. Modify a reshaped view and check if it reflects changes in the original array.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
print(orig_array)  # Original array is changed
print(reshaped_view)

[[100   2   3   4]
 [  5   6   7   8]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [85]:
# 80. Extract a copy of elements greater than 5 and check if modifications affect the original array.

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print(data)  # Original data is unchanged
print(data_copy)

[[2 2 6 8]
 [6 3 9 9]
 [6 6 9 9]]
[100   8   6   9   9   6   6   9   9]


In [86]:
# 81. Perform addition and subtraction between two identical shape matrices.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
sum_matrix = A + B
diff_matrix = A - B
print(sum_matrix)
print(diff_matrix)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [87]:
# 82. Perform matrix multiplication between `C` (3x2) and `D` (2x4).

C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))
product_matrix = np.dot(C, D)
print(product_matrix)

[[20 23 22 13]
 [36 57 50 27]
 [26 65 52 25]]


In [88]:
# 83. Find the transpose of a matrix `E`.

E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T
print(transpose_E)

[[1 4]
 [2 5]
 [3 6]]


In [89]:
# 84. Compute the determinant of a square matrix `F`.

F = np.random.randint(1, 10, (3, 3))
det_F = np.linalg.det(F)
print(det_F)

309.9999999999998


In [90]:
# 85. Find the inverse of a square matrix `G`.

G = np.random.randint(1, 10, (3, 3))
inverse_G = np.linalg.inv(G)
print(inverse_G)

[[-2.   3.  -2. ]
 [-0.5  2.5 -2.5]
 [ 2.5 -4.5  3.5]]
